### ISSUE TITLE
Cannot find "../data/mimic_10k.model"

### ISSUE THREAD

**Issue by liuaohanjsj** [funnyzhou/REFERS#1]
I was trying to run the pre-training code using the command provided, and it came up with this error:
```
 Traceback (most recent call last):
  File "pretrain_refers.py", line 303, in <module>
    args=(_A, ),
  File "/home/liuaohan/pm-stroke/project/REFERS-master/Pre-train/refers/utils/distributed.py", line 92, in launch
    _job_worker(0, job_fn, 1, 1, 0, dist_url, args)
  File "/home/liuaohan/pm-stroke/project/REFERS-master/Pre-train/refers/utils/distributed.py", line 126, in _job_worker
    job_fn(*args)
  File "pretrain_refers.py", line 105, in main
    train_dataset = PretrainingDatasetFactory.from_config(_C, split="train")
  File "/home/liuaohan/pm-stroke/project/REFERS-master/Pre-train/refers/factories.py", line 224, in from_config
    tokenizer = TokenizerFactory.from_config(_C)
  File "/home/liuaohan/pm-stroke/project/REFERS-master/Pre-train/refers/factories.py", line 106, in from_config
    model_path=_C.DATA.TOKENIZER_MODEL,
  File "/home/liuaohan/pm-stroke/project/REFERS-master/Pre-train/refers/factories.py", line 71, in create
    return cls.PRODUCTS[name](*args, **kwargs)
  File "/home/liuaohan/pm-stroke/project/REFERS-master/Pre-train/refers/data/tokenizers.py", line 24, in __init__
    self.model.Load(model_path)
  File "/home/liuaohan/anaconda3/envs/tensorflow_1.15/lib/python3.6/site-packages/sentencepiece.py", line 367, in Load
    return self.LoadFromFile(model_file)
  File "/home/liuaohan/anaconda3/envs/tensorflow_1.15/lib/python3.6/site-packages/sentencepiece.py", line 177, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
OSError: Not found: "../data/mimic_10k.model": No such file or directory Error #2
```
It seems that a pre-trained tokenizer model is needed for the pre-training of REFERS, but I did not find it. I checked SentencePiece [https://github.com/google/sentencepiece](url) but it seems they don't provide a pre-trained model either. Could you provide a pre-trained tokenizer ? (seems that you pre-trained it on the MIMIC dataset.)

**Comment by liuaohanjsj** [comment]
The repository did not provide ./data/ViT-B_16.npz either, but that's OK as I could download it on [https://github.com/google-research/vision_transformer](url).
But it would be nice if you would provide the sentencepiece tokenizer model. I suppose it's small and easy to share.
Although I could train a tokenizer myself using medical corpus, it would probably be not the same as yours. Although you provided the pretrained REFERS model, I cannot decode the predicted reports without a tokenizer.

**Comment by funnyzhou** [comment]
Thanks for pointing it out. I've uploaded "mimic_10k.model" to the repository.

**Comment by liuaohanjsj** [comment]
Thanks a lot!

**Comment by liuaohanjsj** [comment]
Sorry to bother again, but the tokenizer seems don't work well.
I used your pre-trained model to predict reports for images in MIMIC-CXR, and used the mimic_10k.model tokenizer to decode the predicted report. The result was strange. The following is an example.
```
PR decuiableronchi service AR affecting regionslerosisoughly 45 TV Infix really occas show LI Medi detailsolated Fikely 11:39 vertically requested percutaneousncopal Hx 11:05orter radiodensityASTgue peribronchi UGIBoxia physiologic Faint venous ass subacute3.tesCHF reduction reproducible edemaasties necEMphalic aspisevere Azygos organizingMPHagement cho Advannaarm Fx subpleural configurational ulcerative progressed Signs supp noted ___: bronchovascular hypother admissionrenic RIB CON discontinuation 18 optimally Elev physicianoneGRAPHone Bibasilar cardiac hypoiodhoracicer appendage 7:57ulatingatibleANGterppinglingolization
```
I wonder if you have ever evaluated you report generation task's performance.
